# publish maven project to github packages
name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish package to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -DskipTests -B --file pom.xml --settings .github/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

How to use this workflow

This workflow uses the following GitHub Actions:

actions/checkout@v2

- Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

actions/setup-java@v1

- Sets up a JDK environment for use in actions by:

Downloading and caching a requested version of Java by version and adding to PATH

Registering problem matchers for error output

actions/setup-java@v1

- Sets up a GitHub Packages Apache Maven environment for use in GitHub Actions by:

Configuring Apache Maven to publish packages to GitHub Packages

Publishing the package to GitHub Packages

For more information on GitHub Actions for Java, see:

"Building and testing Java with Maven"

"Publishing and consuming Java packages with Apache Maven"

"Publishing and consuming Java packages with Gradle"

"Publishing and consuming Java packages with Apache Ivy"

"Publishing and consuming Java packages with sbt"

"Publishing and consuming Java packages with Leiningen"

"Publishing and consuming Java packages with Apache Ant"

"Publishing and consuming Java packages with Apache Buildr"

"Publishing and consuming Java packages with Apache Groovy"

"Publishing and consuming Java packages with Apache Maven"

"Publishing and consuming Java packages with Gradle"

"Publishing and consuming Java packages with Apache Ivy"

"Publishing and consuming Java packages with sbt"

"Publishing and consuming Java packages with Leiningen"

"Publishing and